"""
verifier.py

Verifies the outputs generated by the previous prompts.
"""

from llm import ask
from prompts import VERIFY_PROMPT


def verify_summary(policy, summary, details, exclusions):
    """
    Verify the generated outputs against the original policy.
    """

    prompt = VERIFY_PROMPT.format(
        policy=policy,
        summary=summary,
        details=details,
        exclusions=exclusions
    )

    response = ask(
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response.choices[0].message.content